[package]
name = "d3q2"
version = "0.1.0"
authors = ["Yu Ri Tan <yuri_tan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
ndarray = "0.15.1"
